### PR TITLE
added 3rd level metadata expansion

### PR DESCRIPTION
**Pull request by uris-tools**
Expanding some fields to show additional level of info:
    "Case Fields" [TAB] will load list of fields
    "Account triggers" [TAB] will load list of triggers
    users [TAB] will load all users.   "users dan" will show matching users for direct access
    "list assets" [TAB] will load all the LISTVIEWS for this object and allow to jump to a listview directly
    run report [TAB] - list of reports
    edit report [TAB]
    setup profiles [TAB] - list of profiles
    Apex Classes [TAB] - list of apex classes

### CODE REVIEW

**Comment by dannysummerlin** [comment]
Hey @uris-tools, sorry I’m so slow at this point, this is looking really good though. I do need to give it a whirl, I’ve just been slammed, but I haven’t forgotten!

**Comment by uris-tools** [comment]
Hi Danny,

No worries.   Not urgent...

In the meantime, I made another change I'd like to push, but I think it
will be easier for you to review them separately.
The PR from last month adds additional levels to the navigation (in
addition to Account->Fields, it adds Account->Fields->Name ,
Account->Fields->Country, etc)

The 2nd change improves (from my point of view) the search.    It is pushed
to my branch , but I did not create a PR for it yet.  It's a big change so
I would prefer to do it after you review the current PR.
Changed SEARCH method · ***@***.***
<https://github.com/dannysummerlin/force-navigator/commit/56495b84e0909ae6e4a6b396937b04cc257a182d>

This changes what happens when you use "?" in the command field.    The
search is done directly in the search box and the results can be clicked to
open the record:
[image: image.png]
Uri

**Comment by dannysummerlin** [comment]
pulling this into improvement branch for verification

**Comment by dannysummerlin** [comment]
So cool! First thoughts:
1. Let's filter out fields like Id, LastActivityDate, etc, the system fields that you can't actually get to the pages of
2. I noticed that after the first load, it starts to auto-load the fields before I have hit Tab, I'd prefer to have it wait, what do you think?

I'm going to keep checking it out, and yeah go ahead and make a PR for the search situation, we might be able to do a both/and and have a setting or something!

**Comment by uris-tools** [comment]
Hi again,

1. I'm not sure I understand "system fields that you can't actually get to
the pages of" ?    I can get to ID field using "Setup > Account > Fields >
ID" or to LastActivity using "Setup > Account > Fields >
lastActivityDate".   This is not working for you?

2. I actually like it like that.   I did change the sorting so that the
fields will appear after the 'higher level' results, but I got used to
entering a user name and accessing it directly.
To explain:
1. "Refresh Metadata"
2."users Danny" -->  It will load the users and then show you relevant
options
3. "Smith" - it will expand to "Users > Joe Smith".  No need to enter
"users"

By the way, Tab is not needed - a delay of 1 second (not entering anything)
is the same as tab.  This is done in debounceGetMoreData()

If you still prefer to change it, no problem.  I can remove it from the
commands cache.

Uri

**Pull request merged**
